import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#793100",
        "on-primary-fixed": "#000767",
        "surface-tint": "#4c56af",
        "on-secondary-fixed-variant": "#354a53",
        "surface-container-lowest": "#ffffff",
        "outline": "#767683",
        "on-primary-container": "#8690ee",
        "outline-variant": "#c6c5d4",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#343d96",
        "on-error": "#ffffff",
        "surface-container-highest": "#e4e1ea",
        "on-tertiary-container": "#fa6d00",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#bdc2ff",
        "on-tertiary-fixed": "#341100",
        "inverse-primary": "#bdc2ff",
        "tertiary": "#331000",
        "secondary": "#4c616c",
        "surface-container-high": "#eae7ef",
        "on-surface-variant": "#454652",
        "surface-bright": "#fbf8ff",
        "on-surface": "#1b1b21",
        "tertiary-fixed-dim": "#ffb691",
        "surface-container-low": "#f5f2fb",
        "on-secondary-container": "#526772",
        "surface": "#fbf8ff",
        "on-primary": "#ffffff",
        "background": "#fbf8ff",
        "primary": "#000666",
        "secondary-fixed": "#cfe6f2",
        "primary-fixed": "#e0e0ff",
        "secondary-fixed-dim": "#b4cad6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#071e27",
        "tertiary-fixed": "#ffdbcb",
        "error-container": "#ffdad6",
        "primary-container": "#2E1A47",
        "tertiary-container": "#542000",
        "secondary-container": "#cfe6f2",
        "on-background": "#1b1b21",
        "surface-container": "#efecf5",
        "inverse-surface": "#303036",
        "inverse-on-surface": "#f2eff8",
        "surface-variant": "#e4e1ea",
        "surface-dim": "#dbd9e1",
        "energy-orange": "#ff6f00",
        "midnight-purple": "#0F071A",
        "midnight-purple-light": "#1A0B2E",
        "starlight-gold": "#FFD700",
        "neon-cyan": "#00F5FF"
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
};
export default config;
